import Link from "next/link";
import { Check, MonitorSmartphone, ShieldCheck, X } from "lucide-react";
import { PageHeader, StatusBadge } from "@/components/ui";
import { listAdminPlans } from "@/data/admin";
import { formatMoney } from "@/lib/format";

export const metadata = { title: "Plans" };

export default async function PlansPage() {
  const plans = await listAdminPlans();
  return <div className="space-y-7"><PageHeader eyebrow="Configuration" title="Plans" description="Control device limits, validation windows, commercial terms, public features, and licensed capabilities." actionLabel="Create plan" actionHref="/admin/plans/new" /><div className="grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.id} className="surface relative overflow-hidden p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><ShieldCheck size={20} /></span><div><h2 className="font-bold">{plan.name}</h2><StatusBadge status={plan.status} /></div></div><p className="mt-5 text-sm leading-6 text-[#667085]">{plan.description}</p><p className="mt-6"><strong className="text-3xl tracking-[-.04em]">{formatMoney(plan.priceInPaise)}</strong><span className="text-sm text-[#98a2b3]"> / {plan.interval.toLowerCase()}</span></p><div className="my-6 h-px bg-[#eaecf0]" /><ul className="space-y-3 text-sm text-[#475467]"><li className="flex gap-2"><MonitorSmartphone size={17} className="shrink-0 text-[#5b4df5]" />Up to {plan.maxDevices} device{plan.maxDevices > 1 ? "s" : ""}</li><li className="flex gap-2"><Check size={17} className="shrink-0 text-[#11966f]" />{plan.validationWindowDays}-day offline window</li><li className="flex gap-2"><Check size={17} className="shrink-0 text-[#11966f]" />Signed offline activation</li><li className="flex gap-2"><Check size={17} className="shrink-0 text-[#11966f]" />{plan.allowOnlineBilling ? "Offline + Online billing enabled" : "Offline billing only"}</li><li className="flex gap-2">{plan.allowCloudBackup ? <Check size={17} className="shrink-0 text-[#11966f]" /> : <X size={17} className="shrink-0 text-rose-500" />}{plan.allowCloudBackup ? "Cloud backup enabled" : "Cloud backup unavailable"}</li><li className="flex gap-2">{plan.allowReportsExports ? <Check size={17} className="shrink-0 text-[#11966f]" /> : <X size={17} className="shrink-0 text-rose-500" />}{plan.allowReportsExports ? "Reports & exports enabled" : "Reports & exports unavailable"}</li>{plan.features.map((feature) => <li key={feature} className="flex gap-2"><Check size={17} className="shrink-0 text-[#11966f]" />{feature}</li>)}</ul><Link href={`/admin/plans/${plan.id}/edit`} className="focus-ring mt-7 block w-full rounded-xl border border-[#dfe3eb] py-2.5 text-center text-sm font-semibold text-[#475467]">Edit plan</Link></article>)}</div>{!plans.length ? <p className="surface p-10 text-center text-sm text-[#667085]">No plans are stored in Supabase.</p> : null}</div>;
}
