import Link from "next/link";
import { Eye, Printer } from "lucide-react";
import { PageHeader, StatusBadge } from "@/components/ui";
import { WorkspaceRequired } from "@/components/workspace-required";
import { listBillingInvoices } from "@/data/billing";
import { formatDate, formatMoney } from "@/lib/format";

export default async function Page() {
  const { business, invoices } = await listBillingInvoices();
  if (!business) return <div className="space-y-7"><PageHeader eyebrow="Billing desk" title="Invoices" description="Set up a workspace before creating invoices." /><WorkspaceRequired /></div>;
  return <div className="space-y-7"><PageHeader eyebrow={business.companyName} title="Invoices" description="Open any invoice to view, print or save it as a customer-ready PDF." actionLabel="Create invoice" actionHref="/billing/invoices/new" /><div className="surface overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#fafbfc] text-[11px] uppercase tracking-wide text-[#98a2b3]"><tr>{["Invoice", "Customer", "Issued", "Total", "Paid", "Balance", "Status"].map((heading) => <th key={heading} className="px-6 py-3">{heading}</th>)}<th className="px-6 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#eef0f4]">{invoices.map((invoice) => <tr key={invoice.id} className="transition hover:bg-[#f7f8f7]"><td className="px-6 py-4"><Link href={`/billing/invoices/${invoice.id}`} className="font-mono text-xs font-semibold text-[#057c73] hover:underline">{invoice.invoiceNumber}</Link></td><td className="px-6 py-4 font-semibold">{invoice.customerName}</td><td className="px-6 py-4 text-[#667085]">{formatDate(invoice.issuedAt)}</td><td className="px-6 py-4">{formatMoney(invoice.totalInPaise)}</td><td className="px-6 py-4 text-emerald-700">{formatMoney(invoice.paidInPaise)}</td><td className="px-6 py-4 text-[#667085]">{formatMoney(invoice.totalInPaise - invoice.paidInPaise)}</td><td className="px-6 py-4"><StatusBadge status={invoice.status} /></td><td className="px-6 py-4"><div className="flex justify-end gap-2"><Link href={`/billing/invoices/${invoice.id}`} className="focus-ring inline-flex h-9 items-center gap-2 border border-[#dfe3e1] px-3 text-[10px] font-bold uppercase tracking-[.08em] text-[#057c73]"><Eye size={14} />View</Link><Link href={`/billing/invoices/${invoice.id}?print=1`} className="focus-ring inline-flex h-9 items-center gap-2 border border-[#dfe3e1] px-3 text-[10px] font-bold uppercase tracking-[.08em] text-[#26272a]"><Printer size={14} />Print</Link></div></td></tr>)}</tbody></table></div>{!invoices.length ? <p className="p-10 text-center text-sm text-[#667085]">No invoices yet.</p> : null}</div></div>;
}
