import Link from "next/link";
import { PageHeader, StatusBadge } from "@/components/ui";
import { listAdminSubscriptionOrders } from "@/data/admin";
import { formatDate, formatMoney } from "@/lib/format";

export const metadata = { title: "Subscriptions" };

export default async function SubscriptionsPage() {
  const orders = await listAdminSubscriptionOrders();
  return <div className="space-y-7"><PageHeader eyebrow="Online sales" title="Subscriptions" description="Review public purchases, Razorpay status, generated customers, and issued licenses." /><div className="surface overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-[#fafbfc] text-[11px] uppercase tracking-wide text-[#98a2b3]"><tr>{["Shop", "Plan", "Amount", "Payment", "Razorpay", "Created", "Records"].map((heading) => <th key={heading} className="px-5 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-[#eef0f4]">{orders.map((order) => <tr key={order.id} className="align-top hover:bg-[#fafaff]"><td className="px-5 py-4"><strong className="block text-[#344054]">{order.companyName}</strong><span className="mt-1 block text-xs text-[#667085]">{order.contactPerson} · {order.phone}</span><span className="block text-xs text-[#98a2b3]">{order.email}</span></td><td className="px-5 py-4 font-medium">{order.planName}</td><td className="px-5 py-4 font-semibold">{formatMoney(order.amountInPaise)}</td><td className="px-5 py-4"><StatusBadge status={order.status} />{order.failureDescription ? <span className="mt-2 block max-w-56 text-xs leading-5 text-rose-700">{order.failureDescription}</span> : null}</td><td className="px-5 py-4 font-mono text-[11px] leading-5 text-[#667085]"><span className="block">Order: {order.razorpayOrderId ?? "—"}</span><span className="block">Payment: {order.razorpayPaymentId ?? "—"}</span><span className="block font-sans">{order.attemptCount} attempt{order.attemptCount === 1 ? "" : "s"}</span></td><td className="px-5 py-4 text-[#667085]">{formatDate(order.createdAt)}{order.paidAt ? <span className="mt-1 block text-xs">Paid {formatDate(order.paidAt)}</span> : null}</td><td className="px-5 py-4"><div className="flex flex-col items-start gap-1">{order.customerId ? <Link className="font-semibold text-[#057c73] hover:underline" href={`/admin/customers/${order.customerId}`}>Customer</Link> : <span className="text-[#98a2b3]">Customer pending</span>}{order.licenseId ? <Link className="font-semibold text-[#057c73] hover:underline" href={`/admin/licenses/${order.licenseId}`}>License</Link> : <span className="text-[#98a2b3]">License pending</span>}</div></td></tr>)}</tbody></table></div>{!orders.length ? <p className="p-10 text-center text-sm text-[#667085]">No public subscription purchases yet.</p> : null}<div className="border-t border-[#eaecf0] px-6 py-4 text-xs text-[#667085]">{orders.length} purchase record{orders.length === 1 ? "" : "s"}</div></div></div>;
}
