"use client";

import Link from "next/link";
import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { createCustomer, createLicense, createPlan, updateCustomer, updatePlan, updatePlatformSettings, type EntityFormState } from "@/app/admin/actions";
import { ThemedDatePicker, ThemedSelect } from "@/components/themed-controls";

const initialState: EntityFormState = {};
const inputClass = "focus-ring h-11 w-full rounded-xl border border-[#dfe3eb] bg-white px-3 text-sm";

function SubmitButton({ label }: { label: string }) {
  const { pending } = useFormStatus();
  return <button disabled={pending} className="focus-ring rounded-xl bg-[#5b4df5] px-5 py-3 text-[11px] font-bold uppercase tracking-[.1em] text-white disabled:opacity-60">{pending ? "Saving…" : label}</button>;
}

function FieldError({ state, name }: { state: EntityFormState; name: string }) {
  return state.errors?.[name]?.[0] ? <span className="mt-1 block text-xs text-rose-600">{state.errors[name][0]}</span> : null;
}

export function CustomerForm({ customer }: { customer?: { id: string; companyName: string; contactPerson: string; email: string; phone: string; address: string; gstin: string | null; status: string } }) {
  const action = customer ? updateCustomer.bind(null, customer.id) : createCustomer;
  const [state, formAction] = useActionState(action, initialState);
  return <form action={formAction} className="surface space-y-5 p-6"><div className="grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Company name</span><input name="companyName" required defaultValue={customer?.companyName} className={inputClass} /><FieldError state={state} name="companyName" /></label><label><span className="mb-2 block text-sm font-semibold">Contact person</span><input name="contactPerson" required defaultValue={customer?.contactPerson} className={inputClass} /><FieldError state={state} name="contactPerson" /></label><label><span className="mb-2 block text-sm font-semibold">Email</span><input name="email" type="email" required defaultValue={customer?.email} className={inputClass} /><FieldError state={state} name="email" /></label><label><span className="mb-2 block text-sm font-semibold">Phone</span><input name="phone" required defaultValue={customer?.phone} className={inputClass} /><FieldError state={state} name="phone" /></label><label><span className="mb-2 block text-sm font-semibold">GSTIN</span><input name="gstin" defaultValue={customer?.gstin ?? ""} className={inputClass} /><FieldError state={state} name="gstin" /></label><label><span className="mb-2 block text-sm font-semibold">Status</span><select name="status" defaultValue={customer?.status ?? "ACTIVE"} className={inputClass}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Address</span><textarea name="address" required defaultValue={customer?.address} rows={4} className="focus-ring w-full rounded-xl border border-[#dfe3eb] bg-white p-3 text-sm" /><FieldError state={state} name="address" /></label></div>{state.message ? <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{state.message}</p> : null}<div className="flex justify-end gap-3 border-t border-[#eaecf0] pt-5"><Link href={customer ? `/admin/customers/${customer.id}` : "/admin/customers"} className="rounded-xl border border-[#dfe3eb] px-5 py-3 text-[11px] font-bold uppercase tracking-[.1em]">Cancel</Link><SubmitButton label={customer ? "Save customer" : "Create customer"} /></div></form>;
}

export function PlanForm({ plan }: { plan?: { id: string; name: string; description: string; maxDevices: number; validationWindowDays: number; priceInPaise: number; interval: string; status: string } }) {
  const action = plan ? updatePlan.bind(null, plan.id) : createPlan;
  const [state, formAction] = useActionState(action, initialState);
  return <form action={formAction} className="surface space-y-5 p-6"><div className="grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Plan name</span><input name="name" required defaultValue={plan?.name} className={inputClass} /><FieldError state={state} name="name" /></label><label><span className="mb-2 block text-sm font-semibold">Price in rupees</span><input name="priceInRupees" type="number" min="0" step="0.01" required defaultValue={plan ? plan.priceInPaise / 100 : 0} className={inputClass} /><FieldError state={state} name="priceInRupees" /></label><label><span className="mb-2 block text-sm font-semibold">Maximum devices</span><input name="maxDevices" type="number" min="1" max="100" required defaultValue={plan?.maxDevices ?? 1} className={inputClass} /></label><label><span className="mb-2 block text-sm font-semibold">Validation window (days)</span><input name="validationWindowDays" type="number" min="1" max="365" required defaultValue={plan?.validationWindowDays ?? 30} className={inputClass} /></label><label><span className="mb-2 block text-sm font-semibold">Billing interval</span><select name="interval" defaultValue={plan?.interval ?? "YEAR"} className={inputClass}><option value="MONTH">Monthly</option><option value="YEAR">Yearly</option></select></label><label><span className="mb-2 block text-sm font-semibold">Status</span><select name="status" defaultValue={plan?.status ?? "ACTIVE"} className={inputClass}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Description</span><textarea name="description" defaultValue={plan?.description} rows={4} className="focus-ring w-full rounded-xl border border-[#dfe3eb] bg-white p-3 text-sm" /></label></div>{state.message ? <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{state.message}</p> : null}<div className="flex justify-end gap-3 border-t border-[#eaecf0] pt-5"><Link href="/admin/plans" className="rounded-xl border border-[#dfe3eb] px-5 py-3 text-[11px] font-bold uppercase tracking-[.1em]">Cancel</Link><SubmitButton label={plan ? "Save plan" : "Create plan"} /></div></form>;
}

export function PlatformSettingsForm({ settings }: { settings: { defaultValidationWindowDays: number; expiryWarningDays: number; licenseIssuer: string } }) {
  const [state, action] = useActionState(updatePlatformSettings, initialState);
  return <form action={action} className="surface space-y-6 p-6"><div><h2 className="font-bold">Default license policy</h2><p className="mt-1 text-sm text-[#667085]">New plans and license workflows can use these defaults.</p></div><div className="grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Offline validation window</span><input name="defaultValidationWindowDays" type="number" min="1" max="365" defaultValue={settings.defaultValidationWindowDays} className={inputClass} /></label><label><span className="mb-2 block text-sm font-semibold">Expiry warning days</span><input name="expiryWarningDays" type="number" min="1" max="365" defaultValue={settings.expiryWarningDays} className={inputClass} /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Activation payload issuer</span><input name="licenseIssuer" type="url" required defaultValue={settings.licenseIssuer} className={inputClass} /><FieldError state={state} name="licenseIssuer" /></label></div>{state.message ? <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{state.message}</p> : null}<div className="flex justify-end border-t border-[#eaecf0] pt-5"><SubmitButton label="Save settings" /></div></form>;
}

export function LicenseForm({ customers, plans, defaultExpiry }: { customers: { id: string; name: string; phone: string }[]; plans: { id: string; name: string; maxDevices: number; validationWindowDays: number }[]; defaultExpiry: string }) {
  const [state, action] = useActionState(createLicense, initialState);
  const customerOptions = customers.map((customer) => ({ value: customer.id, label: customer.name, description: customer.phone }));
  const planOptions = plans.map((plan) => ({ value: plan.id, label: plan.name, description: `${plan.maxDevices} device${plan.maxDevices === 1 ? "" : "s"} · ${plan.validationWindowDays}-day offline window` }));
  return <div className="space-y-5"><form action={action} className="surface space-y-5 p-6"><div className="grid gap-5 sm:grid-cols-2"><div><ThemedSelect name="customerId" label="Customer" options={customerOptions} placeholder="Search customer" required searchable emptyMessage="No active customers found." /><FieldError state={state} name="customerId" /></div><div><ThemedSelect name="planId" label="Plan" options={planOptions} placeholder="Select license plan" required /><FieldError state={state} name="planId" /></div><ThemedDatePicker name="expiresAt" label="License expiry date" defaultValue={defaultExpiry} /></div><p className="border-l-2 border-[#057c73] bg-[#e6f2f0] p-3 text-xs leading-5 text-[#035f58]">Device limit and offline validation window are copied from the selected plan. The plaintext key is revealed only once.</p>{state.message && !state.licenseKey ? <p className="bg-rose-50 p-3 text-sm text-rose-700">{state.message}</p> : null}<div className="flex justify-end gap-3 border-t border-[#eaecf0] pt-5"><Link href="/admin/licenses" className="border border-[#dfe3eb] px-5 py-3 text-[11px] font-bold uppercase tracking-[.1em]">Cancel</Link><SubmitButton label="Generate license" /></div></form>{state.licenseKey ? <section className="border border-amber-300 bg-amber-50 p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-amber-800">Copy now — shown only once</p><code className="mt-3 block break-all font-mono text-2xl font-bold tracking-[.08em] text-[#26272a]">{state.licenseKey}</code><p className="mt-3 text-sm leading-6 text-amber-900">{state.message} Send this key securely to the customer.</p><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={() => navigator.clipboard.writeText(state.licenseKey ?? "")} className="bg-[#057c73] px-4 py-2.5 text-[10px] font-bold uppercase tracking-[.1em] text-white">Copy license key</button><Link href="/activate" target="_blank" className="border border-[#057c73] px-4 py-2.5 text-[10px] font-bold uppercase tracking-[.1em] text-[#035f58]">Test activation</Link>{state.licenseId ? <Link href={`/admin/licenses/${state.licenseId}`} className="border border-amber-400 px-4 py-2.5 text-[10px] font-bold uppercase tracking-[.1em]">Open license</Link> : null}</div></section> : null}</div>;
}
