import Link from "next/link";
import { Check, Monitor, ReceiptIndianRupee, Smartphone } from "lucide-react";

export const metadata = { title: "Billing products" };

const products = [
  { icon: Smartphone, name: "AV Smartbilling Mobile", description: "Fast, offline-first billing for Android phones and shop counters.", features: ["Barcode scanning and quick billing", "A4, WhatsApp and thermal bill sharing", "Products, customers, reports and stock alerts", "Optional cloud backup and online mode"] },
  { icon: Monitor, name: "AV Smartbilling Software", description: "A complete billing workspace for PCs and laptops.", features: ["Professional invoices and payment tracking", "Customer and inventory management", "Business reports and exports", "Secure license and device control"] },
];

export default function ProductsPage() {
  return <main className="min-h-screen bg-[#f7f8f7]"><header className="border-b border-[#dfe3e1] bg-white px-5 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><span className="flex items-center gap-3"><span className="grid size-10 place-items-center bg-[#057c73] text-white"><ReceiptIndianRupee size={22} /></span><strong>AV Smartbilling</strong></span><Link href="/subscribe" className="bg-[#057c73] px-4 py-2.5 text-xs font-bold uppercase tracking-[.08em] text-white">Get activation key</Link></div></header><section className="mx-auto max-w-6xl px-5 py-12 sm:py-16"><div className="max-w-3xl"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#057c73]">Billing made practical</p><h1 className="mt-3 text-4xl tracking-[-.035em] sm:text-5xl">Choose the right billing experience for your shop.</h1><p className="mt-4 text-sm leading-7 text-[#6d716f]">Use the mobile app at the counter or manage billing from a computer. Both products are designed for simple daily use and dependable business records.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-2">{products.map((product) => { const Icon = product.icon; return <article key={product.name} className="border border-[#dfe3e1] bg-white p-6 sm:p-8"><span className="grid size-12 place-items-center bg-[#e6f2f0] text-[#057c73]"><Icon size={25} /></span><h2 className="mt-6 text-2xl">{product.name}</h2><p className="mt-2 text-sm leading-6 text-[#6d716f]">{product.description}</p><ul className="mt-6 space-y-3 text-sm">{product.features.map((feature) => <li key={feature} className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-[#057c73]" />{feature}</li>)}</ul></article>; })}</div><div className="mt-10 border border-[#057c73] bg-[#e6f2f0] p-6 text-center"><h2 className="text-2xl">Ready to activate?</h2><p className="mt-2 text-sm text-[#6d716f]">Purchase a plan securely and receive your activation key immediately after verification.</p><Link href="/subscribe" className="mt-5 inline-flex bg-[#057c73] px-6 py-3 text-xs font-bold uppercase tracking-[.1em] text-white">View plans and purchase</Link></div></section></main>;
}

