import { InventoryAdjustmentForm } from "@/components/inventory-adjustment-form";
import { PageHeader, StatusBadge } from "@/components/ui";
import { getBillingInventory } from "@/data/billing";
import { formatDate, formatMoney } from "@/lib/format";

export default async function Page() {
  const { business, products, movements } = await getBillingInventory();
  return <div className="space-y-7"><PageHeader eyebrow={business?.companyName ?? "Billing desk"} title="Inventory" description="Purchases, returns, sales and corrections with traceable stock history." /><InventoryAdjustmentForm products={products.filter((product) => product.status === "ACTIVE")} /><section className="surface overflow-hidden"><div className="border-b border-[#dfe3e1] px-5 py-4"><h2 className="text-xl font-normal">Current stock</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-[#fafbfa] text-[10px] uppercase tracking-wide text-[#8a908d]"><tr><th className="px-5 py-3">Product</th><th>Category</th><th>Stock</th><th>Low-stock level</th><th>Value at cost</th><th>Status</th></tr></thead><tbody className="divide-y divide-[#edf0ee]">{products.map((product) => <tr key={product.id}><td className="px-5 py-4"><strong>{product.name}</strong><small className="block font-mono text-[10px] text-[#8a908d]">{product.sku}</small></td><td>{product.category || "—"}</td><td className={product.stockQuantity <= product.lowStockThreshold ? "font-semibold text-amber-700" : ""}>{product.stockQuantity} {product.unit}</td><td>{product.lowStockThreshold} {product.unit}</td><td>{formatMoney(Math.round(product.purchasePriceInPaise * product.stockQuantity))}</td><td><StatusBadge status={product.status} /></td></tr>)}</tbody></table></div>{!products.length ? <p className="p-10 text-center text-sm text-[#6d716f]">No products are available.</p> : null}</section><section className="surface overflow-hidden"><div className="border-b border-[#dfe3e1] px-5 py-4"><h2 className="text-xl font-normal">Stock movement history</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-xs"><thead className="bg-[#fafbfa] text-[10px] uppercase tracking-wide text-[#8a908d]"><tr><th className="px-5 py-3">Date</th><th>Product</th><th>Type</th><th>Change</th><th>Balance</th><th>Reference / Notes</th></tr></thead><tbody className="divide-y divide-[#edf0ee]">{movements.map((movement) => <tr key={movement.id}><td className="px-5 py-4">{formatDate(movement.createdAt)}</td><td><strong>{movement.productName}</strong><small className="block font-mono text-[10px] text-[#8a908d]">{movement.sku}</small></td><td><StatusBadge status={movement.movementType} /></td><td className={movement.quantityChange > 0 ? "font-semibold text-[#057c73]" : "font-semibold text-amber-700"}>{movement.quantityChange > 0 ? "+" : ""}{movement.quantityChange} {movement.unit}</td><td>{movement.quantityAfter} {movement.unit}</td><td>{[movement.reference, movement.notes].filter(Boolean).join(" · ") || "—"}</td></tr>)}</tbody></table></div>{!movements.length ? <p className="p-10 text-center text-sm text-[#6d716f]">No stock movements yet.</p> : null}</section></div>;
}
